export const projectRequests = [
    {
        name: 'Sanya Malik',
        email: 'sanya.malik@example.com',
        profilelink: 'https://peerconnect.dev/users/sanyamalik',
        avatar: '',
        requestedOn: '2025-05-20',
        purpose: 'I want to help students by sharing my AI and ML expertise.',
        techStack: ['Python', 'TensorFlow', 'Flask'],
        status: 'pending',
        reviewedBy: null,
    },
    {
        name: 'Dev Arora',
        email: 'dev.arora@example.com',
        profilelink: 'https://peerconnect.dev/users/devarora',
        avatar: '',
        requestedOn: '2025-05-21',
        purpose:
            'Looking to contribute backend features and improve documentation.',
        techStack: ['Node.js', 'Express', 'MongoDB'],
        status: 'pending',
        reviewedBy: null,
    },
    {
        name: 'Aarushi Jain',
        email: 'aarushi.j@example.com',
        profilelink: 'https://peerconnect.dev/users/aarushijain',
        avatar: '',
        requestedOn: '2025-05-18',
        purpose:
            'I’ve built several student-focused apps and want to scale my impact.',
        techStack: ['React', 'Firebase', 'Figma'],
        status: 'approved',
        reviewedBy: 'admin1',
    },
    {
        name: 'Nikhil Bansal',
        email: 'nikhil.b@example.com',
        profilelink: 'https://peerconnect.dev/users/nikhilbansal',
        avatar: '',
        requestedOn: '2025-05-16',
        purpose:
            'Keen to work on the analytics dashboard and optimization tasks.',
        techStack: ['Django', 'PostgreSQL', 'Docker'],
        status: 'rejected',
        reviewedBy: 'admin2',
    },
    {
        name: 'Muskaan Singh',
        email: 'muskaan.singh@example.com',
        profilelink: 'https://peerconnect.dev/users/muskaansingh',
        avatar: '',
        requestedOn: '2025-05-19',
        purpose:
            'Excited to work on frontend designs and accessibility features.',
        techStack: ['HTML', 'CSS', 'JavaScript', 'Vue.js'],
        status: 'pending',
        reviewedBy: null,
    },
    {
        name: 'Yash Thakur',
        email: 'yash.t@example.com',
        profilelink: 'https://peerconnect.dev/users/yashthakur',
        avatar: '',
        requestedOn: '2025-05-22',
        purpose: 'I want to mentor juniors and contribute learning resources.',
        techStack: ['C++', 'DSA', 'Markdown'],
        status: 'approved',
        reviewedBy: 'admin3',
    },
    {
        name: 'Ananya Ghosh',
        email: 'ananya.g@example.com',
        profilelink: 'https://peerconnect.dev/users/ananyaghosh',
        avatar: '',
        requestedOn: '2025-05-17',
        purpose: 'Looking to write tech blogs and create guides for beginners.',
        techStack: ['HTML', 'CSS', 'Markdown', 'Canva'],
        status: 'pending',
        reviewedBy: null,
    },
    {
        name: 'Pranav Iyer',
        email: 'pranav.iyer@example.com',
        profilelink: 'https://peerconnect.dev/users/pranaviyer',
        avatar: '',
        requestedOn: '2025-05-15',
        purpose: 'Interested in helping with testing and bug reports.',
        techStack: ['Jest', 'Cypress', 'JavaScript'],
        status: 'rejected',
        reviewedBy: 'admin1',
    },
];
